
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

desc "Assemble Build"
lane :assemble_build do |options|
    gradle(
        task: "assemble",
        flavor: options[:build_flavor],
        build_type: options[:build_type]
    )
end

desc "Unit Test"
lane :unit_test do |options|
    gradle(
        task: "test",
        flavor: options[:build_flavor],
        build_type: options[:build_type]
    )
end